In [3]:
import numpy as np


In [6]:
arry1=data7=np.arange(0,10)

In [7]:
arry1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arry2=np.zeros([3,3])


In [9]:
arry2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arry3=np.ones([2,3,4])

In [11]:
arry3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
arry4=np.random.randint(0,100,10)

In [14]:
arry4

array([40, 17, 87, 67, 79, 56, 19, 73,  9, 84])

In [17]:
np.random.uniform(0,100,10)

array([13.92200305, 77.75675288, 82.5870572 , 83.81878752, 80.75889281,
       66.15563914, 76.99378866, 89.11438784, 16.0596493 , 10.6164562 ])

In [18]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.arange(1,0,0.25)

array([], dtype=float64)

In [21]:
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [22]:
np.linspace(-1,1,num=5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [25]:
np.arange(-1,1.1,0.25)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [26]:
import numpy as sin

In [27]:
np.sin(np.pi/2.)

1.0

In [28]:
np.sin(np.arange(0,361,90)*np.pi/180)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [30]:
np.cos(np.arange(0,180,90)*np.pi/180)

array([1.000000e+00, 6.123234e-17])