In [2]:
 import numpy as np


In [2]:
arr1=np.array([[1,2],[8,9]])

In [3]:
arr1


array([[1, 2],
       [8, 9]])

In [4]:
arr1*2


array([[ 2,  4],
       [16, 18]])

In [5]:
arr1=np.array([[1,2,3],[8,9,4]])

In [6]:
arr1+5

array([[ 6,  7,  8],
       [13, 14,  9]])

In [7]:
arr1=np.array([[1,2,3,6],[8,9,4,7]])

In [8]:
arr1-10

array([[-9, -8, -7, -4],
       [-2, -1, -6, -3]])

In [9]:
arr1=np.array([[1,2,3,6,8],[8,9,4,7,2]])

In [10]:
arr1/2

array([[0.5, 1. , 1.5, 3. , 4. ],
       [4. , 4.5, 2. , 3.5, 1. ]])

In [19]:
arr1=np.array([[1,2,3,6,8,4],[8,9,4,7,2,3]])

In [15]:
data1= arr1**2

In [16]:
data1

array([[ 1,  4,  9, 36, 64, 16],
       [64, 81, 16, 49,  4,  9]])

In [20]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.44948974, 2.82842712,
        2.        ],
       [2.82842712, 3.        , 2.        , 2.64575131, 1.41421356,
        1.73205081]])

In [24]:
arr1=np.array([[1,2],[8,9]])


In [27]:
np.matmul(arr1,arr1)

array([[17, 20],
       [80, 97]])

In [34]:
arr3=np.array([[1,2,3],[8,9,4],[2,3,4]])

In [35]:
np.dot(arr3,arr3)

array([[ 23,  29,  23],
       [ 88, 109,  76],
       [ 34,  43,  34]])

In [48]:
arr3=np.array([[1,2,3],[8,9,4]])
arr4=np.array([[1,2],[8,9],[2,3]])

In [49]:
np.matmul(arr3,arr4)

array([[ 23,  29],
       [ 88, 109]])

In [6]:
#q11
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1
arr1_transpose = np.transpose(arr1)
arr1_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
#q12
arr1 = np.array([[1, 2, 3,4], [5, 6,7,8],[8,9,10,11]])
arr1
arr1_transpose = np.transpose(arr1)
arr1_transpose

array([[ 1,  5,  8],
       [ 2,  6,  9],
       [ 3,  7, 10],
       [ 4,  8, 11]])

In [20]:
#q13
arr1 = np.array([[1, 2, 3,4,15], [5, 6,7,8,13],[8,9,10,11,14],[12,23,45,2,17],[23,34,1,56,20]])
arr1


array([[ 1,  2,  3,  4, 15],
       [ 5,  6,  7,  8, 13],
       [ 8,  9, 10, 11, 14],
       [12, 23, 45,  2, 17],
       [23, 34,  1, 56, 20]])

In [21]:
arr1_transpose = np.transpose(arr1)
arr1_transpose

array([[ 1,  5,  8, 12, 23],
       [ 2,  6,  9, 23, 34],
       [ 3,  7, 10, 45,  1],
       [ 4,  8, 11,  2, 56],
       [15, 13, 14, 17, 20]])

In [23]:
#q14
arr2=np.array([[1,2],[5,6]])
arr2

array([[1, 2],
       [5, 6]])

In [24]:
arr2_transpose = np.transpose(arr2)
arr2_transpose

array([[1, 5],
       [2, 6]])

In [27]:
arr2_m=np.dot(arr2,arr2)
arr2_m

array([[11, 14],
       [35, 46]])

In [44]:
#q15
A=np.array([[6,2],[5,4]])
A
B=np.array([[7,8],[9,7]])
B
np.dot(A,B)

array([[60, 62],
       [71, 68]])

In [47]:
#q16
C= np.array([[1,2,3],[6,7,8],[7,8,9]])
C
D= np.array([[9,8,7],[6,5,4],[4,4,3]])
D
np.dot(C,D)

array([[ 33,  30,  24],
       [128, 115,  94],
       [147, 132, 108]])

In [51]:
#q17
arr_1=np.array([[1,2,3],[6,7,8]])
arr_1
arr_2=np.array([[1,2],[2,4],[6,8]])
arr_2   
np.dot(arr_1,arr_2)

array([[ 23,  34],
       [ 68, 104]])

In [54]:
#q18
arr_2=np.array([[1,2],[2,4],[6,8]])
arr_2 
arr_1=np.array([[1,2,3],[6,7,8]])
arr_1
np.dot(arr_2,arr_1)

array([[13, 16, 19],
       [26, 32, 38],
       [54, 68, 82]])

In [62]:
#q19
arr_4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
arr4_transpose = np.transpose(arr_4)
arr4_transpose

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [64]:
np.dot(arr_4,arr_4)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [66]:
#q20
arr_5=np.array([[1,2,3,4,0],[5,6,7,8,9],[9,10,11,12,5],[13,14,15,16,20],[23,21,4,54,8]])
arr_5


array([[ 1,  2,  3,  4,  0],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12,  5],
       [13, 14, 15, 16, 20],
       [23, 21,  4, 54,  8]])

In [71]:
inverse_5=np.linalg.inv(arr_5)
inverse_5

array([[ 4.82931122e+15, -6.35435687e+15, -1.77921992e+15,
         3.30426557e+15, -1.82912154e-02],
       [-8.57743337e+15,  1.12860965e+16,  3.16010703e+15,
        -5.86877020e+15,  4.74127557e-02],
       [ 2.66693306e+15, -3.50912245e+15, -9.82554287e+14,
         1.82474368e+15, -3.99518652e-02],
       [ 1.08118908e+15, -1.42261721e+15, -3.98332819e+14,
         7.39760950e+14,  1.08303249e-02],
       [-2.75915420e-01,  4.15678185e-01, -3.61010830e-03,
        -1.36152656e-01,  3.49679764e-18]])

In [74]:
np.dot(inverse_5,inverse_5)

array([[ 7.66537950e+31, -1.00860257e+32, -2.82408718e+31,
         5.24473334e+31, -2.82742118e+14],
       [-1.36146293e+32,  1.79139859e+32,  5.01591604e+31,
        -9.31527265e+31,  5.02183761e+14],
       [ 4.23312002e+31, -5.56989477e+31, -1.55957053e+31,
         2.89634528e+31, -1.56141169e+14],
       [ 1.71612974e+31, -2.25806545e+31, -6.32258325e+30,
         1.17419403e+31, -6.33004741e+13],
       [-5.05476805e+15,  6.65101059e+15,  1.86228297e+15,
        -3.45852551e+15,  2.34249297e-02]])