In [1]:
import numpy as np


In [4]:
#q1
x = np.arange(0,10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[3]

3

In [15]:
#q2
array = np.random.random((3, 3))

In [16]:
element = arr1[2, 1]

In [17]:
element

8

In [ ]:
#q3


In [37]:
array1= np.random.randint(5,size=(4,4))

In [38]:
array1

array([[1, 2, 3, 3],
       [1, 0, 4, 0],
       [2, 3, 0, 4],
       [1, 3, 4, 0]])

In [39]:
element1= array1[:2, 2:]

In [40]:
element1

array([[3, 3],
       [4, 0]])

In [41]:
#q4
x = np.arange(0,10)

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:

x_copy = x[0:3].copy()


In [46]:
x_copy

array([0, 1, 2])

In [47]:
#q5
array1= np.random.randint(5,size=(3,3))

In [48]:
array1

array([[4, 3, 3],
       [0, 2, 3],
       [4, 0, 1]])

In [53]:
array1_copy = array1[:2,:2].copy()

In [54]:
array1_copy

array([[4, 3],
       [0, 2]])

In [59]:
#q6
y =np.arange(0, 9).reshape((3, 3))


In [60]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#q7

In [67]:
array1= np.random.randint(5,size=(4,4))

In [68]:
array1

array([[1, 0, 2, 4],
       [0, 3, 2, 0],
       [2, 3, 2, 3],
       [0, 0, 2, 1]])

In [72]:
array_1d = array1.reshape(-1)

In [73]:
array_1d

array([1, 0, 2, 4, 0, 3, 2, 0, 2, 3, 2, 3, 0, 0, 2, 1])

In [77]:
arr=np.random.randn(5,5)


In [78]:
arr

array([[ 0.79559754, -0.3759316 , -0.46949013, -1.41321948, -1.1412656 ],
       [-0.28884947,  0.22379529,  1.47649044, -0.25080338,  0.97372584],
       [ 0.96344155, -0.67473463,  1.33809547, -0.9757422 ,  0.15429338],
       [-0.64436136, -0.38123752, -0.43312295,  1.38137939,  0.16843753],
       [-0.31764201,  0.29068544,  0.31274068, -0.39338269,  0.58096584]])

In [80]:
arr=4*np.random.randn(5,5)+75


In [81]:
arr

array([[78.55144154, 64.53120777, 70.51756039, 84.38939071, 79.2979849 ],
       [72.83256919, 72.20941998, 76.9177102 , 78.11476154, 81.7519089 ],
       [68.87013601, 77.60786966, 79.58473482, 80.34375075, 77.07005902],
       [79.81946551, 70.57675774, 78.17788599, 71.33963742, 74.7355657 ],
       [75.07712112, 70.75590574, 80.39035114, 73.07356366, 71.62206401]])

In [82]:
A=np.array([-2,5,4,-8,0])

In [83]:
A

array([-2,  5,  4, -8,  0])

In [84]:
np.sort(A) 

array([-8, -2,  0,  4,  5])

In [86]:
np.sort(A)[::-1]

array([ 5,  4,  0, -2, -8])

In [87]:
countries = np.array(['France', 'Germany', 'USA','Russia','USA','Mexico','Germany'])

In [88]:
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [89]:
np.in1d(['France','USA','Sweden'],countries)


array([ True,  True, False])

In [8]:
#q8:
arr_1=np.arange(0,5)
arr_1


array([0, 1, 2, 3, 4])

In [10]:
arr_2=np.arange(0,5)
arr_2


array([0, 1, 2, 3, 4])

In [17]:
l=np.concatenate((arr_1,arr_2)) 
l


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [25]:
#q9
arr_1=np.array([[1,2],[3,4]])
arr_1
arr_2=np.array([[1,2,3],[5,6,7]])
arr_2


array([[1, 2, 3],
       [5, 6, 7]])

In [27]:
np.hstack((arr_1,arr_2))

array([[1, 2, 1, 2, 3],
       [3, 4, 5, 6, 7]])

In [31]:
#q10
arr_1=np.array([[1,2],[3,4]])
arr_1
arr_2=np.array([[1,2],[3,4],[4,5]])
arr_2
np.vstack((arr_1,arr_2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [4, 5]])

In [34]:
#q11
arr_1=np.random.randint(20,size=(4,4))
arr_1
half1,half2=np.split(arr_1,2)


In [35]:
half1

array([[ 9,  8, 11, 15],
       [15, 10,  3, 12]])

In [36]:
half2

array([[13, 18,  0, 19],
       [14,  2, 12,  8]])

In [38]:
#q12
arr_1=np.random.randint(20,size=(4,4))
arr_1
half1,half2=np.split(arr_1,2,axis=1)

In [39]:
half1

array([[15,  1],
       [ 5,  7],
       [ 7, 12],
       [ 6,  5]])

In [40]:
half2

array([[17, 11],
       [ 4,  1],
       [ 2,  7],
       [ 8, 10]])

In [44]:
#q13
arr_1=np.random.randint(20,size=(4,4))
arr_1
subarrays=np.split(arr_1,2,axis=0)
subarrays1,subarrays2=np.split(subarrays[0],2,axis=1)
subarrays3,subarrays4=np.split(subarrays[1],2,axis=1)

In [45]:
subarrays1,subarrays2

(array([[ 8,  2],
        [18,  5]]),
 array([[10, 10],
        [10, 14]]))

In [46]:
subarrays3,subarrays4

(array([[13, 15],
        [ 7, 11]]),
 array([[6, 0],
        [7, 8]]))

In [49]:
#q14
arr_1=np.arange(0,10)
arr_1[arr_1 % 2 !=0] =0
arr_1


array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [58]:
#q15
arr_1=np.random.randint(20,size=(3,3))
arr_1

array([[18, 19,  9],
       [ 2, 18,  4],
       [12, 10, 18]])

In [61]:
arr_1[:1]=0
arr_1


array([[ 0,  0,  0],
       [ 2, 18,  4],
       [12, 10, 18]])

In [62]:
#q16
arr_1=np.random.randint(20,size=(3,3))
arr_1

array([[ 2,  4,  2],
       [ 9,  4, 15],
       [ 5, 19,  2]])

In [65]:
arr_1[:,2:]=0
arr_1

array([[ 2,  4,  0],
       [ 9,  4,  0],
       [ 5, 19,  0]])

In [66]:
#q17
arr_1=np.random.randint(20,size=(3,3))
arr_1

array([[ 0,  8, 11],
       [ 9,  2, 13],
       [ 6,  2, 15]])

In [70]:
arr_1[:2,1:]=0
arr_1

array([[ 0,  0,  0],
       [ 9,  0,  0],
       [ 6,  2, 15]])

In [72]:
#q18
arr_1=np.arange(0,10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr_copy=arr_1.copy()
arr_copy*2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
#q19
arr_1=np.random.rand(3,3)
arr_1

array([[0.96379875, 0.67453056, 0.66981155],
       [0.97957835, 0.47338837, 0.33966164],
       [0.86365827, 0.22792625, 0.66018631]])

In [78]:
arr_copy=arr_1.copy()
arr_copy+1

array([[1.96379875, 1.67453056, 1.66981155],
       [1.97957835, 1.47338837, 1.33966164],
       [1.86365827, 1.22792625, 1.66018631]])

In [80]:
#q20
arr_1=np.random.randint(5,size=(3,3))
arr_1


array([[3, 4, 4],
       [2, 2, 0],
       [2, 0, 1]])

In [82]:
arr1_copy=arr_1[0:2,0:2].copy()
arr1_copy

array([[3, 4],
       [2, 2]])